# Generated by Django 4.2.8 on 2025-12-05 06:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contractors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='services.servicecategory')),
            ],
            options={
                'verbose_name_plural': 'Service Categories',
                'db_table': 'service_categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContractorService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('years_of_experience', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum price for this service', max_digits=10, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum price for this service', max_digits=10, null=True)),
                ('pricing_model', models.CharField(choices=[('hourly', 'Hourly Rate'), ('fixed', 'Fixed Price'), ('quote', 'By Quote')], default='quote', max_length=50)),
                ('trust_score', models.FloatField(default=0.0, help_text='Calculated trust score (0-100)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('total_trust_marks', models.IntegerField(default=0)),
                ('verified_trust_marks', models.IntegerField(default=0)),
                ('trust_score_last_calculated', models.DateTimeField(blank=True, null=True)),
                ('portfolio_images', models.JSONField(blank=True, default=list, help_text='List of portfolio image URLs')),
                ('certifications', models.JSONField(blank=True, default=list, help_text='List of certifications for this service')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('total_jobs', models.IntegerField(default=0)),
                ('views_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contractor_services', to='services.servicecategory')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='contractors.contractorprofile')),
            ],
            options={
                'db_table': 'contractor_services',
                'ordering': ['-trust_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServicePortfolioItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('project_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('client_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='services.contractorservice')),
            ],
            options={
                'db_table': 'service_portfolio_items',
                'ordering': ['display_order', '-created_at'],
                'indexes': [models.Index(fields=['service', 'is_featured'], name='service_por_service_201c5d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='servicecategory',
            index=models.Index(fields=['slug'], name='service_cat_slug_192b5a_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecategory',
            index=models.Index(fields=['is_active'], name='service_cat_is_acti_c27f89_idx'),
        ),
        migrations.AddIndex(
            model_name='contractorservice',
            index=models.Index(fields=['contractor', 'category'], name='contractor__contrac_b551ab_idx'),
        ),
        migrations.AddIndex(
            model_name='contractorservice',
            index=models.Index(fields=['category', '-trust_score'], name='contractor__categor_17a909_idx'),
        ),
        migrations.AddIndex(
            model_name='contractorservice',
            index=models.Index(fields=['is_active', '-trust_score'], name='contractor__is_acti_8ee933_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contractorservice',
            unique_together={('contractor', 'category')},
        ),
    ]
