# Generated by Django 4.2.8 on 2025-12-06 00:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSubcategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predefined_subcategories', to='services.servicecategory')),
            ],
            options={
                'verbose_name_plural': 'Service Subcategories',
                'db_table': 'service_subcategories',
                'ordering': ['category', 'display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='contractorservice',
            name='subcategories',
            field=models.ManyToManyField(blank=True, help_text='Specific subcategories this contractor offers', related_name='contractor_services', to='services.servicesubcategory'),
        ),
        migrations.AddIndex(
            model_name='servicesubcategory',
            index=models.Index(fields=['category', 'is_active'], name='service_sub_categor_f59c26_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='servicesubcategory',
            unique_together={('category', 'slug')},
        ),
    ]
