# Generated by Django 4.2.8 on 2025-12-05 06:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudPattern',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pattern_type', models.CharField(choices=[('rapid_burst', 'Rapid Trust Burst'), ('identical_text', 'Identical Review Text'), ('ip_cluster', 'IP Address Clustering'), ('coordinated_attack', 'Coordinated Attack'), ('fake_accounts', 'Fake Account Network'), ('review_manipulation', 'Review Manipulation')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('description', models.TextField()),
                ('confidence_score', models.FloatField(help_text='AI confidence in fraud detection (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('evidence', models.JSONField(default=dict)),
                ('is_resolved', models.BooleanField(default=False)),
                ('action_taken', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fraud_patterns',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('quality_rating', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('communication_rating', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('timeliness_rating', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('value_rating', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('project_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('project_duration_days', models.IntegerField(blank=True, null=True)),
                ('sentiment_score', models.FloatField(default=0.0, help_text='AI-analyzed sentiment (-1 to 1)', validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)])),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('key_themes', models.JSONField(blank=True, default=list)),
                ('helpful_count', models.IntegerField(default=0)),
                ('not_helpful_count', models.IntegerField(default=0)),
                ('is_flagged', models.BooleanField(default=False)),
                ('flag_reason', models.TextField(blank=True, null=True)),
                ('is_verified_purchase', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrustScoreHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trust_score', models.FloatField()),
                ('total_trust_marks', models.IntegerField()),
                ('verified_trust_marks', models.IntegerField()),
                ('raw_score', models.FloatField()),
                ('smoothed_score', models.FloatField()),
                ('experience_bonus', models.FloatField()),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('contractor_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_score_history', to='services.contractorservice')),
            ],
            options={
                'db_table': 'trust_score_history',
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='TrustMark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether this trust has job proof/verification')),
                ('verification_proof', models.FileField(blank=True, help_text='Job completion proof (photos, invoice, etc.)', null=True, upload_to='trust_verification/')),
                ('review_text', models.TextField(blank=True, help_text='Optional short review', max_length=1000, null=True)),
                ('weight', models.FloatField(default=1.0, help_text='Diminishing weight based on repeat trusts')),
                ('contribution_score', models.FloatField(default=0.0, help_text='Calculated contribution to overall trust score')),
                ('trust_number_for_customer', models.IntegerField(default=1, help_text='Which number trust this is from same customer to same service')),
                ('status', models.CharField(choices=[('active', 'Active'), ('flagged', 'Flagged'), ('disputed', 'Disputed'), ('removed', 'Removed'), ('under_review', 'Under Review')], default='active', max_length=20)),
                ('is_flagged_as_fraud', models.BooleanField(default=False)),
                ('fraud_confidence', models.FloatField(default=0.0, help_text='AI-calculated fraud likelihood (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('flag_reason', models.TextField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('device_fingerprint', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contractor_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_marks', to='services.contractorservice')),
            ],
            options={
                'db_table': 'trust_marks',
                'ordering': ['-created_at'],
            },
        ),
    ]
