# Generated by Django 4.2.8 on 2025-12-05 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trust', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trustmark',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_trust_marks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trustmark',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_trust_marks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='contractor_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='services.contractorservice'),
        ),
        migrations.AddField(
            model_name='review',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='trust_mark',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detailed_review', to='trust.trustmark'),
        ),
        migrations.AddField(
            model_name='fraudpattern',
            name='affected_contractor_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fraud_patterns', to='services.contractorservice'),
        ),
        migrations.AddField(
            model_name='fraudpattern',
            name='affected_trust_marks',
            field=models.ManyToManyField(related_name='fraud_patterns', to='trust.trustmark'),
        ),
        migrations.AddField(
            model_name='fraudpattern',
            name='affected_users',
            field=models.ManyToManyField(related_name='fraud_patterns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fraudpattern',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_fraud_patterns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='trustscorehistory',
            index=models.Index(fields=['contractor_service', '-calculated_at'], name='trust_score_contrac_5a36ee_idx'),
        ),
        migrations.AddIndex(
            model_name='trustmark',
            index=models.Index(fields=['contractor_service', 'status', '-created_at'], name='trust_marks_contrac_8a7cc7_idx'),
        ),
        migrations.AddIndex(
            model_name='trustmark',
            index=models.Index(fields=['customer', '-created_at'], name='trust_marks_custome_3251fe_idx'),
        ),
        migrations.AddIndex(
            model_name='trustmark',
            index=models.Index(fields=['status'], name='trust_marks_status_4590f2_idx'),
        ),
        migrations.AddIndex(
            model_name='trustmark',
            index=models.Index(fields=['is_flagged_as_fraud'], name='trust_marks_is_flag_c1d574_idx'),
        ),
        migrations.AddIndex(
            model_name='trustmark',
            index=models.Index(fields=['-created_at'], name='trust_marks_created_7e5812_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['contractor_service', '-created_at'], name='reviews_contrac_66815c_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['customer', '-created_at'], name='reviews_custome_ae4813_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating'], name='reviews_rating_17e8a4_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudpattern',
            index=models.Index(fields=['pattern_type', '-detected_at'], name='fraud_patte_pattern_aa0ec6_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudpattern',
            index=models.Index(fields=['severity', 'is_resolved'], name='fraud_patte_severit_6130bf_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudpattern',
            index=models.Index(fields=['-detected_at'], name='fraud_patte_detecte_33923d_idx'),
        ),
    ]
