# Generated by Django 4.2.8 on 2025-12-05 06:23

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('profile_views', models.IntegerField(default=0)),
                ('search_appearances', models.IntegerField(default=0)),
                ('contact_clicks', models.IntegerField(default=0)),
                ('trust_marks_received', models.IntegerField(default=0)),
                ('average_trust_score', models.FloatField(default=0.0)),
                ('local_rank', models.IntegerField(blank=True, null=True)),
                ('category_rank', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'contractor_analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ContractorDispute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dispute_type', models.CharField(choices=[('unfair_trust', 'Unfair Trust Mark'), ('fraudulent_review', 'Fraudulent Review'), ('identity_theft', 'Identity Theft'), ('other', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='open', max_length=20)),
                ('description', models.TextField()),
                ('evidence', models.FileField(blank=True, null=True, upload_to='dispute_evidence/')),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contractor_disputes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('business_registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('business_license', models.FileField(blank=True, null=True, upload_to='contractor_licenses/')),
                ('office_location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('office_address', models.CharField(max_length=500)),
                ('service_radius_km', models.FloatField(default=20.0, help_text='Service radius in kilometers', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(200.0)])),
                ('is_identity_verified', models.BooleanField(default=False)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('verification_document', models.FileField(blank=True, null=True, upload_to='verification_docs/')),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('verification_expires_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('years_in_business', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('company_size', models.CharField(blank=True, max_length=50, null=True)),
                ('insurance_verified', models.BooleanField(default=False)),
                ('insurance_document', models.FileField(blank=True, null=True, upload_to='insurance_docs/')),
                ('website', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('is_accepting_jobs', models.BooleanField(default=True)),
                ('average_response_time_hours', models.FloatField(default=24.0)),
                ('total_jobs_completed', models.IntegerField(default=0)),
                ('profile_views', models.IntegerField(default=0)),
                ('contact_clicks', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contractor_profiles',
            },
        ),
    ]
