# Generated by Django 4.2.8 on 2025-12-05 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contractors', '0001_initial'),
        ('trust', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractordispute',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='contractors.contractorprofile'),
        ),
        migrations.AddField(
            model_name='contractordispute',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_disputes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractordispute',
            name='trust_mark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='trust.trustmark'),
        ),
        migrations.AddField(
            model_name='contractoranalytics',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='contractors.contractorprofile'),
        ),
        migrations.AddIndex(
            model_name='contractorprofile',
            index=models.Index(fields=['verification_status'], name='contractor__verific_2fc8e8_idx'),
        ),
        migrations.AddIndex(
            model_name='contractorprofile',
            index=models.Index(fields=['is_identity_verified'], name='contractor__is_iden_853347_idx'),
        ),
        migrations.AddIndex(
            model_name='contractorprofile',
            index=models.Index(fields=['is_accepting_jobs'], name='contractor__is_acce_7c6a7c_idx'),
        ),
        migrations.AddIndex(
            model_name='contractordispute',
            index=models.Index(fields=['contractor', '-created_at'], name='contractor__contrac_1e29d0_idx'),
        ),
        migrations.AddIndex(
            model_name='contractordispute',
            index=models.Index(fields=['status'], name='contractor__status_904b46_idx'),
        ),
        migrations.AddIndex(
            model_name='contractordispute',
            index=models.Index(fields=['dispute_type'], name='contractor__dispute_1aea6d_idx'),
        ),
        migrations.AddIndex(
            model_name='contractoranalytics',
            index=models.Index(fields=['contractor', '-date'], name='contractor__contrac_4571a4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contractoranalytics',
            unique_together={('contractor', 'date')},
        ),
    ]
