# Generated by Django 4.2.8 on 2025-12-05 06:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('approve_trust', 'Approve Trust Mark'), ('remove_trust', 'Remove Trust Mark'), ('ban_user', 'Ban User'), ('unban_user', 'Unban User'), ('verify_contractor', 'Verify Contractor'), ('reject_verification', 'Reject Verification'), ('resolve_dispute', 'Resolve Dispute'), ('flag_fraud', 'Flag Fraud')], max_length=50)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'admin_actions',
                'ordering': ['-created_at'],
            },
        ),
    ]
