# Generated by Django 4.2.8 on 2025-12-05 06:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchRankingCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('normalized_trust_score', models.FloatField(default=0.0)),
                ('normalized_experience', models.FloatField(default=0.0)),
                ('overall_rank_score', models.FloatField(default=0.0)),
                ('category_rank', models.IntegerField(blank=True, null=True)),
                ('local_rank', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('contractor_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_cache', to='services.contractorservice')),
            ],
            options={
                'db_table': 'search_ranking_cache',
                'indexes': [models.Index(fields=['-overall_rank_score'], name='search_rank_overall_6114b1_idx'), models.Index(fields=['contractor_service'], name='search_rank_contrac_d21c6b_idx')],
            },
        ),
    ]
